// Requires an externally installed Playwright; no browser dependency is deployed.
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const {chromium} = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({headless: true,
  executablePath: process.env.CHROMIUM_EXECUTABLE || undefined,
  args: process.env.CHROMIUM_EXECUTABLE ? ['--no-sandbox', '--disable-dev-shm-usage'] : []});
const page = await browser.newPage({viewport: {width: 1280, height: 1000}});
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
page.on('dialog', dialog => dialog.accept());
try {
  await page.goto('http://127.0.0.1:8080/');
  await page.getByLabel('Administrator-Passwort').fill(process.env.BADGER_TEST_PASSWORD);
  await page.getByRole('button', {name: 'Hub öffnen'}).click();
  await page.getByRole('button', {name: '+ App registrieren', exact: true}).click();
  await page.getByLabel('App-ID', {exact: true}).fill('energie');
  await page.getByLabel('Name auf dem Display').fill('Energie');
  await page.getByRole('button', {name: 'App speichern'}).click();
  await page.getByRole('button', {name: 'Gesichert · schließen'}).click();
  await page.getByRole('button', {name: '+ Gerät hinzufügen', exact: true}).click();
  await page.getByLabel('Geräte-ID', {exact: true}).fill('flur');
  await page.getByLabel('Gerätename', {exact: true}).fill('Badger im Flur');
  await page.locator('#assignments').getByLabel('Energie', {exact: true}).check();
  await page.getByRole('button', {name: 'Gerät speichern'}).click();
  await page.getByRole('button', {name: 'Gesichert · schließen'}).click();
  await page.locator('#devices').getByRole('heading', {name: 'Badger im Flur'}).waitFor();
  assert.equal(await page.locator('#app-count').textContent(), '1');
  assert.equal(await page.locator('#device-count').textContent(), '1');
  await page.locator('#apps').getByRole('button', {name: 'Bearbeiten'}).click();
  const editor = page.locator('#page-editor');
  await editor.getByLabel('Seitentitel', {exact: true}).fill('Solar');
  assert.equal(await editor.locator('#editor-preview-title').textContent(), 'Solar');
  await editor.getByRole('button', {name: 'Seite hinzufügen', exact: true}).click();
  await editor.getByLabel('Seitentitel', {exact: true}).fill('Bitaxe');
  await editor.getByLabel('Bezeichnung', {exact: true}).fill('Hashrate');
  await editor.getByLabel('Wert', {exact: true}).fill('1100 GH/s');
  await editor.getByRole('button', {name: 'Zeile hinzufügen', exact: true}).click();
  await editor.locator('#row-1-label').fill('Leistung');
  await editor.locator('#row-1-value').fill('18.5 W');
  await editor.getByRole('button', {name: 'Seite nach vorne', exact: true}).click();
  assert.equal(await editor.getByLabel('Seite auswählen').inputValue(), '0');
  await editor.getByRole('button', {name: 'Zeile 2 entfernen', exact: true}).click();
  await editor.getByLabel('Seite auswählen').selectOption('1');
  assert.equal(await editor.getByLabel('Seitentitel', {exact: true}).inputValue(), 'Solar');
  await editor.getByText('Erweitert: JSON bearbeiten', {exact: true}).click();
  const goodJson = await editor.getByLabel('Seiten und Werte (JSON)').inputValue();
  await editor.getByLabel('Seiten und Werte (JSON)').fill('{invalid');
  await editor.getByRole('button', {name: 'JSON übernehmen', exact: true}).click();
  await editor.getByText('Seiten enthalten kein gültiges JSON.').waitFor();
  assert.equal(await editor.getByLabel('Seitentitel', {exact: true}).isDisabled(), true);
  await page.getByRole('button', {name: 'App speichern', exact: true}).click();
  await page.getByText('JSON-Änderungen zuerst übernehmen oder verwerfen.', {exact: true}).waitFor();
  await editor.getByRole('button', {name: 'JSON-Änderungen verwerfen', exact: true}).click();
  assert.equal(await editor.getByLabel('Seiten und Werte (JSON)').inputValue(), goodJson);
  const oversized = JSON.parse(goodJson); oversized[0].title = 'x'.repeat(29);
  await editor.getByLabel('Seiten und Werte (JSON)').fill(JSON.stringify(oversized));
  await editor.getByRole('button', {name: 'JSON übernehmen', exact: true}).click();
  await editor.getByText('Seite 1: Titel benötigt 1–28 druckbare ASCII-Zeichen.').waitFor();
  await editor.getByRole('button', {name: 'JSON-Änderungen verwerfen', exact: true}).click();
  // Hidden page errors must block submission and return to that page.
  await editor.getByLabel('Seitentitel', {exact: true}).fill('');
  await editor.getByLabel('Seite auswählen').selectOption('0');
  await page.getByRole('button', {name: 'App speichern', exact: true}).click();
  await page.getByText('Bitte die Eingaben auf Seite 2 korrigieren.', {exact: true}).waitFor();
  await editor.getByLabel('Seitentitel', {exact: true}).fill('Solar');
  await editor.getByLabel('Seite auswählen').selectOption('0');
  await page.getByRole('button', {name: 'App speichern', exact: true}).click();
  await page.getByText('App gespeichert.', {exact: true}).waitFor();
  await page.locator('#apps').getByRole('button', {name: 'Bearbeiten'}).click();
  assert.equal(await editor.getByLabel('Seitentitel', {exact: true}).inputValue(), 'Bitaxe');
  assert.equal(await editor.getByLabel('Wert', {exact: true}).inputValue(), '1100 GH/s');
  // A full six-page import round-trips without losing fields or order.
  await editor.getByText('Erweitert: JSON bearbeiten', {exact: true}).click();
  const six = Array.from({length: 6}, (_, index) => ({title: `Seite ${index+1}`, rows: [{label: 'A', value: 'B'}]}));
  await editor.getByLabel('Seiten und Werte (JSON)').fill(JSON.stringify(six));
  await editor.getByRole('button', {name: 'JSON übernehmen', exact: true}).click();
  assert.equal(await editor.getByRole('button', {name: 'Seite hinzufügen', exact: true}).isDisabled(), true);
  for (let index = 0; index < 5; index++) await editor.getByRole('button', {name: 'Seite entfernen', exact: true}).click();
  assert.equal(await editor.getByRole('button', {name: 'Seite entfernen', exact: true}).isDisabled(), true);
  for (let index = 0; index < 2; index++) await editor.getByRole('button', {name: 'Zeile hinzufügen', exact: true}).click();
  assert.equal(await editor.getByRole('button', {name: 'Zeile hinzufügen', exact: true}).isDisabled(), true);
  await editor.getByLabel('Seitentitel', {exact: true}).fill('Bitaxe');
  await mkdir('test-results', {recursive: true});
  await page.screenshot({path: 'test-results/editor-desktop.png'});
  await page.setViewportSize({width: 390, height: 844});
  assert.equal(await page.locator('#app-dialog').evaluate(element => element.scrollWidth <= element.clientWidth), true);
  await page.screenshot({path: 'test-results/editor-mobile.png'});
  await page.setViewportSize({width: 1280, height: 1000});
  await page.getByRole('button', {name: 'Abbrechen', exact: true}).click();
  await page.locator('#apps').getByRole('button', {name: 'Schlüssel erneuern'}).click();
  await page.getByRole('button', {name: 'Gesichert · schließen'}).click();
  await page.getByRole('button', {name: 'Liste neu laden'}).click();
  await page.getByText('Liste aktualisiert.', {exact: true}).waitFor();
  await mkdir('test-results', {recursive: true});
  await page.screenshot({path: 'test-results/desktop.png', fullPage: true});
  await page.setViewportSize({width: 390, height: 844});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({path: 'test-results/mobile.png', fullPage: true});
  await page.getByRole('button', {name: 'Abmelden', exact: true}).click();
  await page.getByRole('button', {name: 'Hub öffnen'}).waitFor();
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: login, app/device creation, assignment, live editor, ordering, limits, JSON round-trip, hidden-page validation, rotation, reload, logout, mobile overflow; no console errors.');
} finally { await browser.close(); }
